### ISSUE TITLE
Required option to preinstall os specific libraries (yum libs) before building gems

### ISSUE THREAD

**Issue by ponnusamygit** [navarasu/serverless-ruby-layer#14]
Mostly in custom dockerfile, we install necessary yum libraries. For e.g, for pg gem, we install `postgresql-devel` yum package before doing bundle install. 
So need to option to specify a list of yums to be installed rather than specifying docker file

```yml
custom:
  rubyLayer:
    use_docker: true
    docker_yums:
      - postgresql-devel
```
