### ISSUE TITLE
Building via docker on GitHub actions?

### ISSUE THREAD

**Issue by NARKOZ** [navarasu/serverless-ruby-layer#37]
Currently when I try to run `sls deploy` on github actions it fails with:

```
Serverless: Zipping the gemfiles and native libs to /home/runner/work/repo/repo/.serverless/ruby_layer/gemLayer.zip
 
 Exception -----------------------------------------------
 
  [OperationalError: EACCES: permission denied, scandir '/home/runner/work/repo/repo/.serverless/ruby_layer/build/ruby/2.7.0/gems/pg-1.2.3/ext/.gem.20210317-1-q5o5ls'] {
    cause: [Error: EACCES: permission denied, scandir '/home/runner/work/repo/repo/.serverless/ruby_layer/build/ruby/2.7.0/gems/pg-1.2.3/ext/.gem.20210317-1-q5o5ls'] {
      errno: -13,
      code: 'EACCES',
      syscall: 'scandir',
      path: '/home/runner/work/repo/repo/.serverless/ruby_layer/build/ruby/2.7.0/gems/pg-1.2.3/ext/.gem.20210317-1-q5o5ls'
    },
    isOperational: true,
    errno: -13,
    code: 'EACCES',
    syscall: 'scandir',
    path: '/home/runner/work/repo/repo/.serverless/ruby_layer/build/ruby/2.7.0/gems/pg-1.2.3/ext/.gem.20210317-1-q5o5ls'
  }
```

My serverless config contains:

```yml
custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    native_libs:
      - /usr/lib64/libpq.so.5
      - /usr/lib64/libldap_r-2.4.so.2
      - /usr/lib64/liblber-2.4.so.2
      - /usr/lib64/libsasl2.so.3
      - /usr/lib64/libssl3.so
      - /usr/lib64/libsmime3.so
      - /usr/lib64/libnss3.so
```

 - OS: ubuntu-latest
 - NodeVersion 15.10.0
 - Ruby version 2.7.1
 - Bundler version 2.2.6
