### ISSUE TITLE
Trouble deploying `pg` due to `pg_ext.so`

### ISSUE THREAD

**Issue by jagthedrummer** [navarasu/serverless-ruby-layer#38]
**Describe the bug**

I'm trying to follow the example for deploying the `pg` gem, but I'm not having much luck. I have the gem in my `Gemfile` and I've activated Docker and have included `libpq.so.5` as shown in the example.

When I `require 'pg'` I get this error:

```
libldap_r-2.4.so.2: cannot open shared object file: No such file or directory - /opt/ruby/2.7.0/gems/pg-1.2.3/lib/pg_ext.so
```

In trying to debug the problem I've added some code to show the files in `/opt/ruby/2.7.0/gems/pg-1.2.3/lib` and `pg_ext.so` does seem to be there.

```
Files in /opt/ruby/2.7.0/gems/pg-1.2.3/lib
/opt/ruby/2.7.0/gems/pg-1.2.3/lib/pg
/opt/ruby/2.7.0/gems/pg-1.2.3/lib/pg.rb
/opt/ruby/2.7.0/gems/pg-1.2.3/lib/pg_ext.so
```

I've also noticed that there seem to be three copies of the file in `gemLayer.zip`. (Not sure if that matters.)

```
$ unzip -l .serverless/ruby_layer/gemLayer.zip  | grep pg_ext
   567056  04-01-2021 02:53   ruby/2.7.0/gems/pg-1.2.3/ext/pg_ext.so
   567056  04-01-2021 02:53   ruby/2.7.0/gems/pg-1.2.3/lib/pg_ext.so
   567056  04-01-2021 02:53   ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.2.3/pg_ext.so
```

**Error Stack Trace**

Error is just at runtime, not deploy time.

**Example Config files**

Gemfile:
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'aws-sdk-lambda', '~> 1.62'
gem 'aws-sdk-sqs', '~> 1.37'
gem 'aws-sdk-dynamodb', '~> 1.60'
gem 'aws-sdk-ssm', '~> 1.107'

gem 'pg', '~> 1.1'

gem 'activerecord', '~> 6.1', '>= 6.1.3.1'

gem 'pusher'
```

serverless.yml:
```
...
custom:
  rubyLayer:
    use_docker: true
    docker_yums:
      - postgresql-devel
      - postgresql-libs
    native_libs:
      - /usr/lib64/libpq.so.5
...
```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - NodeVersion: 15.11.0
 - Ruby version 2.7.2
 - Bundler version 2.1.4

**Additional context**

None that seems relevant. Happy to provide additional info if there are specifics anyone would like to ask for.

**Comment by jagthedrummer** [comment]
I finally realized I was reading the error backwards. It's not `pg_ext.so` that was missing, it was `libldap_r-2.4.so.2`. After much trial and error I ended up getting things to work with this expanded list of `native_libs`.

```
custom:
  rubyLayer:
    use_docker: true
    docker_yums:
      - postgresql-devel
    native_libs:
      - /usr/lib64/libpq.so.5
      - /usr/lib64/libldap_r-2.4.so.2
      - /usr/lib64/liblber-2.4.so.2
      - /usr/lib64/libsasl2.so.3
      - /usr/lib64/libssl3.so
      - /usr/lib64/libsmime3.so
      - /usr/lib64/libnss3.so
```
