### ISSUE TITLE
Add ignore_gemfile_lock option to ignore Gemfile.lock while building gem layer

### ISSUE THREAD

**Issue by navarasu** [navarasu/serverless-ruby-layer#46]
Currently, by default, the `Gemfile.lock` is used while building the gem layer.
There should be an option to ignore if we don't want to consider it.

```yml
custom:
  rubyLayer:
    ignore_gemfile_lock: true
```
