### ISSUE TITLE
Docker command not found when run on Github Actions

### ISSUE THREAD

**Issue by douglasdoro** [navarasu/serverless-ruby-layer#63]
Hi.

When i try to deploy using Github Actions, the docker command does't work inside serverless-ruby-layer container: "docker command not found." 

Local works fine. 

**Error Stack Trace**
```
Run serverless/github-action@master
/usr/bin/docker run --name a7afdfa700d0a34bd0a58de72731e56b87_4abc12 --label 9916a7 --workdir /github/workspace --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e SLS_DEBUG -e INPUT_ARGS -e INPUT_ENTRYPOINT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/bin/sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ruby-serverless/ruby-serverless":"/github/workspace" 9916a7:afdfa700d0a34bd0a58de72731e56b87 -c "sls plugin install -n serverless-ruby-layer && sls deploy"
Serverless: Installing plugin "serverless-ruby-layer@latest" (this might take a few seconds...)
Serverless: Successfully installed "serverless-ruby-layer@latest"
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command rubylayer
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [AWS sts 200 0.149s 0 retries] getCallerIdentity({})
Serverless: Clearing previous build ruby layer build
 
 Error ---------------------------------------------------
 
  Error: docker command not found. Please install docker https://www.docker.com/products/docker-desktop
      at ServerlessRubyBundler.bundleInstall (/github/workspace/node_modules/serverless-ruby-layer/lib/bundle.js:61:13)
      at ServerlessRubyBundler.tryCatcher (/github/workspace/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/github/workspace/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/github/workspace/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/github/workspace/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/github/workspace/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/github/workspace/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/github/workspace/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/github/workspace/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/github/workspace/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.3
     Framework Version:         2.71.0
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1
```
**Config files**

serverless.yml  
````

service: ruby-serverless

frameworkVersion: '2'

plugins:
  - serverless-ruby-layer
custom:
  rubyLayer:
    use_docker: true
    docker_yums:
      - postgresql-devel
    native_libs:
      - /usr/lib64/libpq.so.5
      - /usr/lib64/libldap_r-2.4.so.2
      - /usr/lib64/liblber-2.4.so.2
      - /usr/lib64/libsasl2.so.3
      - /usr/lib64/libssl3.so
      - /usr/lib64/libsmime3.so
      - /usr/lib64/libnss3.so
      
provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

package:
 patterns:
   - '!node_modules'

functions:
  hello:
    handler: handler.hello
````
Gemfile
````
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "pg"
````
deploy.yml
```
name: Deploy SLS

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "sls plugin install -n serverless-ruby-layer && sls deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: '*'
```

**Desktop:**
 - OS: Mac OS
 - NodeVersion: 16.13.1 
 - Ruby version: 2.7.0
 - Bundler version: 2.1.2
