### ISSUE TITLE
Clean up and test env pass through & build args with single parameter

### ISSUE THREAD

**Issue by navarasu** [navarasu/serverless-ruby-layer#68]
Use generic name `environment` replacing `docker_build_args` and `docker_env_variable`

docker_env_variable and docker_build_args will use same `environment` option

```yml
custom:
  rubyLayer:
    use_docker: true
    environment:
      -ENVIRONMENT_VARIABLE
      -ENVIRONMENT_VARIABLE=env_value
```
