### ISSUE TITLE
Passing environment to dockerfile in serverless v3 + not working

### ISSUE THREAD

**Issue by starverdiyev** [navarasu/serverless-ruby-layer#93]
**Describe the bug**
In serverless v3+ was changed CLI environment. Now to pass ENV need to use --param. More info: `https://www.serverless.com/framework/docs/guides/parameters`

After this change it's not possible to pass env to serverless-ruby-layer Dockerfile

**Error Stack Trace**

```
Environment: linux, node 14.21.3, framework 3.35.2, plugin 7.0.5, SDK 4.4.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: this.options.environment.forEach is not a function
    at ServerlessRubyBundler.bundleInstall (/home/runner/work/project/project/node_modules/serverless-ruby-layer/lib/bundle.js:97:34)
```

**Example Config files**
Dockerfile:

```
ARG GH_PACKAGE_TOKEN
ENV GH_PACKAGE_TOKEN=${GH_PACKAGE_TOKEN}

RUN bundle config set https://rubygems.pkg.github.com username:${GH_PACKAGE_TOKEN}
```
serverless.yml:

```
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    environment:
      GH_PACKAGE_TOKEN: ${param:gh_package_token} 
```
Deploy run:

`sls deploy --verbose  --param="gh_package_token=${{ secrets.GH_PACKAGES_SECRET }}" 
`

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04
 - NodeVersion: 14.21.13
 - Ruby version: 2.7.1
 - Bundler version:  2.2.17

**Additional context**

In the serverless v2+ env was passing with this config, which was works fine

```
custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    environment:
      - GH_PACKAGE_TOKEN=${opt:gh_package_token, 'default'}
```

`sls deploy --stage --gh_package_token ${{ secrets.GH_PACKAGES_SECRET }}
`

In version v3+ this config was deprecated, and we catch this error:

Error:
Detected unrecognized CLI options: "--gh_package_token".

**Comment by starverdiyev** [comment]
@navarasu can you please take a look for this bug? It's stopped work, because I can't sent token to Dockerfile. Thank you!

**Comment by navarasu** [comment]
```yml
service: use-docker-file-with-environment

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    environment:
      - GH_PACKAGE_TOKEN: ${param:gh_package_token} 
```

The parameter has to be configured in this format ```- GH_PACKAGE_TOKEN: ${param:gh_package_token} ```

**Comment by navarasu** [comment]
I verified this example, 
https://github.com/navarasu/serverless-ruby-layer/tree/master/examples/use-docker-file-with-environment
by mentioning the params.  
```yml
service: use-docker-file-with-environment

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    environment:
      - USE_HTTPARTY
      - NOKOGIRI_VERSION=${param:version}

provider:
  name: aws
  runtime: ruby3.2

functions:
  hello:
    handler: handler.hello
```
Passed the passed the version
```sh
sls deploy  --param="version=1.13.10"
```
It works 👍🏼
